/// pack_telem_defines.h
/// Last autogenerated: Sat Feb 23 17:39:14 2019

#include "globals.h"
#include "config.h"

#define	TELEM_ITEM_0	((uint32_t) (valve_states*1)) >> 0 
#define	TELEM_ITEM_1	((uint32_t) (valve_states*1)) >> 8 
#define	TELEM_ITEM_2	((uint32_t) (valve_states*1)) >> 16 
#define	TELEM_ITEM_3	((uint32_t) (valve_states*1)) >> 24 
#define	TELEM_ITEM_4	((int16_t) (pressure[0]*1)) >> 0 
#define	TELEM_ITEM_5	((int16_t) (pressure[0]*1)) >> 8 
#define	TELEM_ITEM_6	((int16_t) (pressure[1]*1)) >> 0 
#define	TELEM_ITEM_7	((int16_t) (pressure[1]*1)) >> 8 
#define	TELEM_ITEM_8	((int16_t) (pressure[2]*1)) >> 0 
#define	TELEM_ITEM_9	((int16_t) (pressure[2]*1)) >> 8 
#define	TELEM_ITEM_10	((int16_t) (pressure[3]*1)) >> 0 
#define	TELEM_ITEM_11	((int16_t) (pressure[3]*1)) >> 8 
#define	TELEM_ITEM_12	((int16_t) (pressure[4]*1)) >> 0 
#define	TELEM_ITEM_13	((int16_t) (pressure[4]*1)) >> 8 
#define	TELEM_ITEM_14	((int16_t) (pressure[5]*1)) >> 0 
#define	TELEM_ITEM_15	((int16_t) (pressure[5]*1)) >> 8 
#define	TELEM_ITEM_16	((int16_t) (pressure[6]*1)) >> 0 
#define	TELEM_ITEM_17	((int16_t) (pressure[6]*1)) >> 8 
#define	TELEM_ITEM_18	((int16_t) (pressure[7]*1)) >> 0 
#define	TELEM_ITEM_19	((int16_t) (pressure[7]*1)) >> 8 
#define	TELEM_ITEM_20	((int16_t) (pressure[8]*1)) >> 0 
#define	TELEM_ITEM_21	((int16_t) (pressure[8]*1)) >> 8 
#define	TELEM_ITEM_22	((int16_t) (pressure[9]*1)) >> 0 
#define	TELEM_ITEM_23	((int16_t) (pressure[9]*1)) >> 8 
#define	TELEM_ITEM_24	((int16_t) (pressure[10]*1)) >> 0 
#define	TELEM_ITEM_25	((int16_t) (pressure[10]*1)) >> 8 
#define	TELEM_ITEM_26	((int16_t) (pressure[11]*1)) >> 0 
#define	TELEM_ITEM_27	((int16_t) (pressure[11]*1)) >> 8 
#define	TELEM_ITEM_28	((int16_t) (pressure[12]*1)) >> 0 
#define	TELEM_ITEM_29	((int16_t) (pressure[12]*1)) >> 8 
#define	TELEM_ITEM_30	((int16_t) (pressure[13]*1)) >> 0 
#define	TELEM_ITEM_31	((int16_t) (pressure[13]*1)) >> 8 
#define	TELEM_ITEM_32	((int16_t) (pressure[14]*1)) >> 0 
#define	TELEM_ITEM_33	((int16_t) (pressure[14]*1)) >> 8 
#define	TELEM_ITEM_34	((int16_t) (pressure[15]*1)) >> 0 
#define	TELEM_ITEM_35	((int16_t) (pressure[15]*1)) >> 8 
#define	TELEM_ITEM_36	((int16_t) (pressure[16]*1)) >> 0 
#define	TELEM_ITEM_37	((int16_t) (pressure[16]*1)) >> 8 
#define	TELEM_ITEM_38	((int16_t) (pressure[17]*1)) >> 0 
#define	TELEM_ITEM_39	((int16_t) (pressure[17]*1)) >> 8 
#define	TELEM_ITEM_40	((int16_t) (pressure[18]*1)) >> 0 
#define	TELEM_ITEM_41	((int16_t) (pressure[18]*1)) >> 8 
#define	TELEM_ITEM_42	((int16_t) (pressure[19]*1)) >> 0 
#define	TELEM_ITEM_43	((int16_t) (pressure[19]*1)) >> 8 
#define	TELEM_ITEM_44	((int16_t) (pressure[20]*1)) >> 0 
#define	TELEM_ITEM_45	((int16_t) (pressure[20]*1)) >> 8 
#define	TELEM_ITEM_46	((int16_t) (pressure[21]*1)) >> 0 
#define	TELEM_ITEM_47	((int16_t) (pressure[21]*1)) >> 8 
#define	TELEM_ITEM_48	((uint32_t) (samplerate*1)) >> 0 
#define	TELEM_ITEM_49	((uint32_t) (samplerate*1)) >> 8 
#define	TELEM_ITEM_50	((uint32_t) (samplerate*1)) >> 16 
#define	TELEM_ITEM_51	((uint32_t) (samplerate*1)) >> 24 
#define	TELEM_ITEM_52	((uint16_t) (main_cycle_time[0]*1)) >> 0 
#define	TELEM_ITEM_53	((uint16_t) (main_cycle_time[0]*1)) >> 8 
#define	TELEM_ITEM_54	((uint16_t) (motor_cycle_time[0]*1)) >> 0 
#define	TELEM_ITEM_55	((uint16_t) (motor_cycle_time[0]*1)) >> 8 
#define	TELEM_ITEM_56	((uint16_t) (adc_cycle_time[0]*1)) >> 0 
#define	TELEM_ITEM_57	((uint16_t) (adc_cycle_time[0]*1)) >> 8 
#define	TELEM_ITEM_58	((uint32_t) (telemetry_cycle_time[0]*1)) >> 0 
#define	TELEM_ITEM_59	((uint32_t) (telemetry_cycle_time[0]*1)) >> 8 
#define	TELEM_ITEM_60	((uint32_t) (telemetry_cycle_time[0]*1)) >> 16 
#define	TELEM_ITEM_61	((uint32_t) (telemetry_cycle_time[0]*1)) >> 24 
#define	TELEM_ITEM_62	((int16_t) (ebatt*1000)) >> 0 
#define	TELEM_ITEM_63	((int16_t) (ebatt*1000)) >> 8 
#define	TELEM_ITEM_64	((int16_t) (ibus*100)) >> 0 
#define	TELEM_ITEM_65	((int16_t) (ibus*100)) >> 8 
#define	TELEM_ITEM_66	((uint16_t) (telemetry_rate[0]*1)) >> 0 
#define	TELEM_ITEM_67	((uint16_t) (telemetry_rate[0]*1)) >> 8 
#define	TELEM_ITEM_68	((uint8_t) (STATE*1)) >> 0 
#define	TELEM_ITEM_69	((uint8_t) (ivlv[0]*10)) >> 0 
#define	TELEM_ITEM_70	((uint8_t) (ivlv[1]*10)) >> 0 
#define	TELEM_ITEM_71	((uint8_t) (ivlv[2]*10)) >> 0 
#define	TELEM_ITEM_72	((uint8_t) (ivlv[3]*10)) >> 0 
#define	TELEM_ITEM_73	((uint8_t) (ivlv[4]*10)) >> 0 
#define	TELEM_ITEM_74	((uint8_t) (ivlv[5]*10)) >> 0 
#define	TELEM_ITEM_75	((uint8_t) (ivlv[6]*10)) >> 0 
#define	TELEM_ITEM_76	((uint8_t) (ivlv[7]*10)) >> 0 
#define	TELEM_ITEM_77	((uint8_t) (ivlv[8]*10)) >> 0 
#define	TELEM_ITEM_78	((uint8_t) (ivlv[9]*10)) >> 0 
#define	TELEM_ITEM_79	((uint8_t) (ivlv[10]*10)) >> 0 
#define	TELEM_ITEM_80	((uint8_t) (ivlv[11]*10)) >> 0 
#define	TELEM_ITEM_81	((uint8_t) (ivlv[12]*10)) >> 0 
#define	TELEM_ITEM_82	((uint8_t) (ivlv[13]*10)) >> 0 
#define	TELEM_ITEM_83	((uint8_t) (ivlv[14]*10)) >> 0 
#define	TELEM_ITEM_84	((uint8_t) (ivlv[15]*10)) >> 0 
#define	TELEM_ITEM_85	((uint8_t) (ivlv[16]*10)) >> 0 
#define	TELEM_ITEM_86	((uint8_t) (ivlv[17]*10)) >> 0 
#define	TELEM_ITEM_87	((uint8_t) (ivlv[18]*10)) >> 0 
#define	TELEM_ITEM_88	((uint8_t) (ivlv[19]*10)) >> 0 
#define	TELEM_ITEM_89	((uint8_t) (ivlv[20]*10)) >> 0 
#define	TELEM_ITEM_90	((uint8_t) (ivlv[21]*10)) >> 0 
#define	TELEM_ITEM_91	((uint8_t) (ivlv[22]*10)) >> 0 
#define	TELEM_ITEM_92	((uint8_t) (ivlv[23]*10)) >> 0 
#define	TELEM_ITEM_93	((uint8_t) (ivlv[24]*10)) >> 0 
#define	TELEM_ITEM_94	((uint8_t) (ivlv[25]*10)) >> 0 
#define	TELEM_ITEM_95	((uint8_t) (ivlv[26]*10)) >> 0 
#define	TELEM_ITEM_96	((uint8_t) (ivlv[27]*10)) >> 0 
#define	TELEM_ITEM_97	((uint8_t) (ivlv[28]*10)) >> 0 
#define	TELEM_ITEM_98	((uint8_t) (ivlv[29]*10)) >> 0 
#define	TELEM_ITEM_99	((uint8_t) (ivlv[30]*10)) >> 0 
#define	TELEM_ITEM_100	((uint8_t) (ivlv[31]*10)) >> 0 
#define	TELEM_ITEM_101	((uint8_t) (evlv[0]*10)) >> 0 
#define	TELEM_ITEM_102	((uint8_t) (evlv[1]*10)) >> 0 
#define	TELEM_ITEM_103	((uint8_t) (evlv[2]*10)) >> 0 
#define	TELEM_ITEM_104	((uint8_t) (evlv[3]*10)) >> 0 
#define	TELEM_ITEM_105	((uint8_t) (evlv[4]*10)) >> 0 
#define	TELEM_ITEM_106	((uint8_t) (evlv[5]*10)) >> 0 
#define	TELEM_ITEM_107	((uint8_t) (evlv[6]*10)) >> 0 
#define	TELEM_ITEM_108	((uint8_t) (evlv[7]*10)) >> 0 
#define	TELEM_ITEM_109	((uint8_t) (evlv[8]*10)) >> 0 
#define	TELEM_ITEM_110	((uint8_t) (evlv[9]*10)) >> 0 
#define	TELEM_ITEM_111	((uint8_t) (evlv[10]*10)) >> 0 
#define	TELEM_ITEM_112	((uint8_t) (evlv[11]*10)) >> 0 
#define	TELEM_ITEM_113	((uint8_t) (evlv[12]*10)) >> 0 
#define	TELEM_ITEM_114	((uint8_t) (evlv[13]*10)) >> 0 
#define	TELEM_ITEM_115	((uint8_t) (evlv[14]*10)) >> 0 
#define	TELEM_ITEM_116	((uint8_t) (evlv[15]*10)) >> 0 
#define	TELEM_ITEM_117	((uint8_t) (evlv[16]*10)) >> 0 
#define	TELEM_ITEM_118	((uint8_t) (evlv[17]*10)) >> 0 
#define	TELEM_ITEM_119	((uint8_t) (evlv[18]*10)) >> 0 
#define	TELEM_ITEM_120	((uint8_t) (evlv[19]*10)) >> 0 
#define	TELEM_ITEM_121	((uint8_t) (evlv[20]*10)) >> 0 
#define	TELEM_ITEM_122	((uint8_t) (evlv[21]*10)) >> 0 
#define	TELEM_ITEM_123	((uint8_t) (evlv[22]*10)) >> 0 
#define	TELEM_ITEM_124	((uint8_t) (evlv[23]*10)) >> 0 
#define	TELEM_ITEM_125	((uint8_t) (evlv[24]*10)) >> 0 
#define	TELEM_ITEM_126	((uint8_t) (evlv[25]*10)) >> 0 
#define	TELEM_ITEM_127	((uint8_t) (evlv[26]*10)) >> 0 
#define	TELEM_ITEM_128	((uint8_t) (evlv[27]*10)) >> 0 
#define	TELEM_ITEM_129	((uint8_t) (evlv[28]*10)) >> 0 
#define	TELEM_ITEM_130	((uint8_t) (evlv[29]*10)) >> 0 
#define	TELEM_ITEM_131	((uint8_t) (evlv[30]*10)) >> 0 
#define	TELEM_ITEM_132	((uint8_t) (evlv[31]*10)) >> 0 
#define	TELEM_ITEM_133	((int32_t) (e3v*100)) >> 0 
#define	TELEM_ITEM_134	((int32_t) (e3v*100)) >> 8 
#define	TELEM_ITEM_135	((int32_t) (e3v*100)) >> 16 
#define	TELEM_ITEM_136	((int32_t) (e3v*100)) >> 24 
#define	TELEM_ITEM_137	((int32_t) (e5v*100)) >> 0 
#define	TELEM_ITEM_138	((int32_t) (e5v*100)) >> 8 
#define	TELEM_ITEM_139	((int32_t) (e5v*100)) >> 16 
#define	TELEM_ITEM_140	((int32_t) (e5v*100)) >> 24 
#define	TELEM_ITEM_141	((int16_t) (e28v*100)) >> 0 
#define	TELEM_ITEM_142	((int16_t) (e28v*100)) >> 8 
#define	TELEM_ITEM_143	((uint8_t) (i5v*100)) >> 0 
#define	TELEM_ITEM_144	((uint8_t) (i3v*100)) >> 0 
#define	TELEM_ITEM_145	((uint16_t) (BOARD_ID*1)) >> 0 
#define	TELEM_ITEM_146	((uint16_t) (BOARD_ID*1)) >> 8 
#define	TELEM_ITEM_147	((uint16_t) (last_packet_number*1)) >> 0 
#define	TELEM_ITEM_148	((uint16_t) (last_packet_number*1)) >> 8 
#define	TELEM_ITEM_149	((uint16_t) (last_command_id*1)) >> 0 
#define	TELEM_ITEM_150	((uint16_t) (last_command_id*1)) >> 8 
#define	TELEM_ITEM_151	((uint16_t) (tbrd*10)) >> 0 
#define	TELEM_ITEM_152	((uint16_t) (tbrd*10)) >> 8 
#define	TELEM_ITEM_153	((uint16_t) (tvlv*10)) >> 0 
#define	TELEM_ITEM_154	((uint16_t) (tvlv*10)) >> 8 
#define	TELEM_ITEM_155	((uint16_t) (tmtr*10)) >> 0 
#define	TELEM_ITEM_156	((uint16_t) (tmtr*10)) >> 8 
#define	TELEM_ITEM_157	((uint8_t) (error_code*1)) >> 0 
#define	TELEM_ITEM_158	((uint8_t) (LOGGING_ACTIVE*1)) >> 0 
#define	TELEM_ITEM_159	((uint16_t) (logfile->current_page*1)) >> 0 
#define	TELEM_ITEM_160	((uint16_t) (logfile->current_page*1)) >> 8 
#define	TELEM_ITEM_161	((int16_t) (tc[0]*1)) >> 0 
#define	TELEM_ITEM_162	((int16_t) (tc[0]*1)) >> 8 
#define	TELEM_ITEM_163	((uint16_t) (tc[1]*1)) >> 0 
#define	TELEM_ITEM_164	((uint16_t) (tc[1]*1)) >> 8 
#define	TELEM_ITEM_165	((uint16_t) (tc[2]*1)) >> 0 
#define	TELEM_ITEM_166	((uint16_t) (tc[2]*1)) >> 8 
#define	TELEM_ITEM_167	((uint16_t) (tc[3]*1)) >> 0 
#define	TELEM_ITEM_168	((uint16_t) (tc[3]*1)) >> 8 
#define	TELEM_ITEM_169	((uint16_t) (tc[4]*1)) >> 0 
#define	TELEM_ITEM_170	((uint16_t) (tc[4]*1)) >> 8 
#define	TELEM_ITEM_171	((uint16_t) (tc[5]*1)) >> 0 
#define	TELEM_ITEM_172	((uint16_t) (tc[5]*1)) >> 8 
#define	TELEM_ITEM_173	((uint16_t) (tc[6]*1)) >> 0 
#define	TELEM_ITEM_174	((uint16_t) (tc[6]*1)) >> 8 
#define	TELEM_ITEM_175	((uint16_t) (tc[7]*1)) >> 0 
#define	TELEM_ITEM_176	((uint16_t) (tc[7]*1)) >> 8 
#define	TELEM_ITEM_177	((uint16_t) (tc[8]*1)) >> 0 
#define	TELEM_ITEM_178	((uint16_t) (tc[8]*1)) >> 8 
#define	TELEM_ITEM_179	((uint16_t) (tc[9]*1)) >> 0 
#define	TELEM_ITEM_180	((uint16_t) (tc[9]*1)) >> 8 
#define	TELEM_ITEM_181	((uint16_t) (tc[10]*1)) >> 0 
#define	TELEM_ITEM_182	((uint16_t) (tc[10]*1)) >> 8 
#define	TELEM_ITEM_183	((uint16_t) (tc[11]*1)) >> 0 
#define	TELEM_ITEM_184	((uint16_t) (tc[11]*1)) >> 8 
#define	TELEM_ITEM_185	((uint16_t) (tc[12]*1)) >> 0 
#define	TELEM_ITEM_186	((uint16_t) (tc[12]*1)) >> 8 
#define	TELEM_ITEM_187	((uint16_t) (tc[13]*1)) >> 0 
#define	TELEM_ITEM_188	((uint16_t) (tc[13]*1)) >> 8 
#define	TELEM_ITEM_189	((uint16_t) (tc[14]*1)) >> 0 
#define	TELEM_ITEM_190	((uint16_t) (tc[14]*1)) >> 8 
#define	TELEM_ITEM_191	((uint16_t) (tc[15]*1)) >> 0 
#define	TELEM_ITEM_192	((uint16_t) (tc[15]*1)) >> 8 
#define	TELEM_ITEM_193	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_194	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_195	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_196	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_197	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_198	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_199	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_200	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_201	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_202	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_203	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_204	((uint8_t) (0*1)) >> 0 
#define	TELEM_ITEM_205	0
#define	TELEM_ITEM_206	0
#define	TELEM_ITEM_207	0
#define	TELEM_ITEM_208	0
#define	TELEM_ITEM_209	0
#define	TELEM_ITEM_210	0
#define	TELEM_ITEM_211	0
#define	TELEM_ITEM_212	0
#define	TELEM_ITEM_213	0
#define	TELEM_ITEM_214	0
#define	TELEM_ITEM_215	0
#define	TELEM_ITEM_216	0
#define	TELEM_ITEM_217	0
#define	TELEM_ITEM_218	0
#define	TELEM_ITEM_219	0
#define	TELEM_ITEM_220	0
#define	TELEM_ITEM_221	0
#define	TELEM_ITEM_222	0
#define	TELEM_ITEM_223	0
#define	TELEM_ITEM_224	0
#define	TELEM_ITEM_225	0
#define	TELEM_ITEM_226	0
#define	TELEM_ITEM_227	0
#define	TELEM_ITEM_228	0
#define	TELEM_ITEM_229	0
#define	TELEM_ITEM_230	0
#define	TELEM_ITEM_231	0
#define	TELEM_ITEM_232	0
#define	TELEM_ITEM_233	0
#define	TELEM_ITEM_234	0
#define	TELEM_ITEM_235	0
#define	TELEM_ITEM_236	0
#define	TELEM_ITEM_237	0
#define	TELEM_ITEM_238	0
#define	TELEM_ITEM_239	0
#define	TELEM_ITEM_240	0
#define	TELEM_ITEM_241	0
#define	TELEM_ITEM_242	0
#define	TELEM_ITEM_243	0
#define	TELEM_ITEM_244	0
#define	TELEM_ITEM_245	0
#define	TELEM_ITEM_246	0
#define	TELEM_ITEM_247	0
#define	TELEM_ITEM_248	0
#define	TELEM_ITEM_249	0
#define	TELEM_ITEM_250	0
#define	TELEM_ITEM_251	0
#define	TELEM_ITEM_252	0
#define	TELEM_ITEM_253	0
#define	PACKET_SIZE	205
